# Generated by Django 3.2.5 on 2021-07-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.users'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserTasks',
        ),
    ]
