# Generated by Django 3.2.5 on 2021-07-16 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20210716_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
