# Generated by Django 3.2.5 on 2021-07-31 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20210716_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='client',
            new_name='customer',
        ),
    ]
