# Generated by Django 3.2.5 on 2021-07-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210731_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Planning'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-startDate'], 'verbose_name': 'Tâche'},
        ),
    ]
